version: 2
registries:
  npm-redirect-test:
    type: npm-registry
    url: https://flow-talk-view-celebrity.trycloudflare.com
    token: ${{secrets.NPM_REGISTRY_SECRET_3}}
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    registries:
      - npm-redirect-test
